#!/bin/bash

if [[ "$1" == "--help" ]]; then
	echo "Usage: $(basename "$0") [--help] [--verbose]" >&2
	echo >&2
	echo -e "--verbose\tShow the full diffs.">&2
	exit 0
fi
verbose=
if [[ "$1" == "--verbose" ]]; then
	verbose=1
fi

function fetchScript {
	local separator="?"
	[[ "$1" =~ \? ]] && separator="&"

	# shellcheck disable=SC1003
	curl -s "$1${separator}action=raw" | sed -e '$a\' /dev/stdin
}

basePath="$(dirname "$(dirname "$0")")"

declare -A scriptToPage
scriptToPage[activeSysops.js]='https://meta.wikimedia.org/wiki/User:Hoo_man/active_sysops.js'
scriptToPage[enhancedDelete.js]='https://meta.wikimedia.org/wiki/User:Hoo_man/enhancedDelete.js'
scriptToPage[instantNewPagePatrol.js]='https://en.wikipedia.org/wiki/User:Hoo_man/instantNewPagePatrol.js'
scriptToPage[shared.js]='https://meta.wikimedia.org/w/index.php?title=User:Hoo_man/functions.js'
scriptToPage[shared.css]='https://meta.wikimedia.org/w/index.php?title=User:Hoo_man/tool.css'
scriptToPage[smartRollback.js]='https://meta.wikimedia.org/wiki/User:Hoo_man/smart_rollback.js'
scriptToPage[stewardVote.js]='https://meta.wikimedia.org/w/index.php?title=User:Hoo_man/stewardVote.js'
scriptToPage[tagger-core.js]='https://meta.wikimedia.org/w/index.php?title=User:Hoo_man/tagger-core.js'
scriptToPage[tagger.js]='https://meta.wikimedia.org/w/index.php?title=User:Hoo_man/tagger.js'
scriptToPage[usefulLinks.js]='https://meta.wikimedia.org/w/index.php?title=User:Hoo_man/useful_links.js'

exitCode=0
for script in "${!scriptToPage[@]}"; do
	pageContent="$(fetchScript "${scriptToPage[$script]}")"
	diff="$(diff "$basePath/$script" /dev/fd/55 55<<<"$pageContent")"
	if [[ "$diff" =~ .+ ]]; then
		exitCode=1
		echo "Mismatch between \"$script\" and \"${scriptToPage[$script]}\"."
		test -n "$verbose" && echo -e "Diff:\n$diff"
	fi
done

exit "$exitCode"
